version: '3.8'
name: pypi

services:
  pypi:
    image: codermattie/pypi:11
    container_name: pypi-server

    read_only: true
    cap_drop:
      - ALL

    security_opt:
      - no-new-privileges:true

    user: python:python
    working_dir: /home

    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - packages:/home/packages
      - /home/mattie/code/run/pypi/htpasswd:/home/htpasswd

    tmpfs:
      - /run
      - /tmp

volumes:
  packages:
