version: '3'
services:
  pypi:
    image: codermattie/pypi:11
    container_name: pypi-server
    ports:
      - 8080:8080
    volumes:
      - packages:/home/packages
      - ./htpasswd:/home/htpasswd
volumes:
  packages:
