version: '3.8'
name: pypi

services:
  pypi:
    image: codermattie/pypi:11
    container_name: pypi-server
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - packages:/home/packages
      - ./htpasswd:/home/htpasswd
    tmpfs:
      - /run
      - /tmp

volumes:
  packages:
